apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kluster-capacity
spec:
  version: {{ .TagName }}
  homepage: https://github.com/k-cloud-labs/kluster-capacity
  shortDescription: Cluster capacity analysis tool support capacity estimation, cluster compression, scheduler simulation, fragmentation analysis and resource overview.
  description: |
    A simple CLI that support capacity estimation, cluster compression, scheduler simulation, fragmentation analysis and resource overview.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    bin: kluster-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/k-cloud-labs/kluster-capacity/releases/download/{{ .TagName }}/kluster-capacity_{{ .TagName }}_darwin_x86_64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    bin: kluster-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/k-cloud-labs/kluster-capacity/releases/download/{{ .TagName }}/kluster-capacity_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    bin: kluster-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/k-cloud-labs/kluster-capacity/releases/download/{{ .TagName }}/kluster-capacity_{{ .TagName }}_linux_x86_64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    bin: kluster-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/k-cloud-labs/kluster-capacity/releases/download/{{ .TagName }}/kluster-capacity_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}