- name: Retest
  if: startsWith(github.event.comment.body, '/retest')
  uses: actions/github-script@v3
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      github.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: 'Retesting...'
      });
      const branch = context.payload.pull_request.head.ref;
      const event_type = 'pull_request';
      const client_payload = {
        retest: 'true'
      };
      const new_workflow_run = await github.actions.createWorkflowDispatch({
        owner: context.repo.owner,
        repo: context.repo.repo,
        workflow_id: '${{ github.event.workflow.id }}',
        ref: branch,
        inputs: {},
        ref_type: event_type,
        client_payload: client_payload
      });
      console.log(new_workflow_run);
